### ISSUE TITLE
button onclick will not work because of csp

### ISSUE THREAD

**Issue by h0ru5** [zmyaro/crx-options-page#2]
the popup in your example page refuses to work in our project:

Refused to execute inline event handler because it violates the following Content Security Policy directive: "script-src 'self' chrome-extension-resource:".

Regards

**Comment by zmyaro** [comment]
I do not want to increase potential confusion by adding a new file for one line of JavaScript.  Since developers will create their own options page scripts regardless (for loading and saving options, if nothing else), I only added a brief warning about the CSP to the demo page in https://github.com/zmyaro/crx-options-page/commit/9bb73b94ba15fa0bc601825bc784e4712a0d48c3.
